baseURL = 'https://minirah.github.io/'
languageCode = 'en-us'
title = "Minirah's blog"
theme = 'nostyleplease'

[params]
[params.theme_config]
    back_home_text = ".."
    date_format = "2006-01-02"
    appearance = "light"
